person:
  name: chenyi
  age: 24

spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://118.126.64.165:3306/springboot?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC
    username: root
    password: LCode1996.
    driver-class-name: com.mysql.jdbc.Driver
---
spring:
  profiles: dev
server:
  port: 8888
---
spring:
  profiles: pro
server:
  port: 8887


